apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edu_sharing_projects_wlo_bird_mdm_provider.name" . }}-env
  labels: {{ include "edu_sharing_projects_wlo_bird_mdm_provider.labels.app" . | nindent 4 }}
type: Opaque
data:
  APPLICATION_BASIC_AUTH_USER: "{{ .Values.config.auth.username | b64enc }}"
  APPLICATION_BASIC_AUTH_PASSWORD: "{{ default .Values.global.password .Values.config.auth.password | b64enc }}"
  EDU_SHARING_USER: "{{ .Values.config.repository.username | b64enc }}"
  EDU_SHARING_PASSWORD: "{{ default .Values.global.password .Values.config.repository.password | b64enc }}"
